name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
          submodules: true

      - name: Get contributors
        run: |
          git checkout master -- .all-contributorsrc
          cp .all-contributorsrc docs/data/contributors.json

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          extended: true

      - name: Build
        run: |
          cd docs
          hugo --minify --enableGitInfo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          force_orphan: true
          enable_jekyll: true
          publish_branch: gh-pages
