on:
  push:
    branches-ignore:
      - allcontributors/**
  pull_request:
    branches-ignore:
      - allcontributors/**

name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [macos-latest] # , windows-latest // TODO: Review Tests on windows
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

  coverage:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run ./...  --out-format checkstyle > golangci.xml

      - name: Test
        run: |
          go test -cover -coverprofile=coverage.out $(go list ./... | grep -v "*docker*" | grep -e "hostctl/")
          go tool cover -func=coverage.out

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
